version: '3.8'

services:
  ffc-ahwr-farmer-apply:
    command: npm run start:watch
    build:
      target: development
    image: ffc-ahwr-farmer-apply-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/

  zap-baseline-scan:
    image: owasp/zap2docker-stable:2.11.1
    command: zap-baseline.py -t http://ffc-ahwr-farmer-apply:${PORT:-3000} -c config/zap.conf -r test-output/zap-report.html -a -d -I
    depends_on:
      - ffc-ahwr-farmer-apply
    volumes:
      - ./test-output/:/zap/wrk/test-output/
      - ./zap/:/zap/wrk/config/