version: "3.8"

services:
  ffc-future-grants-apply:
    build:
      context: .
      target: production
    image: ffc-future-grants-apply
    container_name: ffc-future-grants-apply
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-future-grants-apply-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      APPLICATIONREQUEST_QUEUE_ADDRESS: ${APPLICATIONREQUEST_QUEUE_ADDRESS:-ffc-ahwr-application-request}${MESSAGE_QUEUE_SUFFIX}
      APPLICATIONRESPONSE_QUEUE_ADDRESS: ${APPLICATIONRESPONSE_QUEUE_ADDRESS:-ffc-ahwr-application-response}${MESSAGE_QUEUE_SUFFIX}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      EVENT_QUEUE_ADDRESS: ${EVENT_QUEUE_ADDRESS:-ffc-ahwr-event}${MESSAGE_QUEUE_SUFFIX}
      GOOGLE_TAG_MANAGER_KEY: ${GOOGLE_TAG_MANAGER_KEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      NOTIFY_TEMPLATE_ID_FARMER_APPLY_LOGIN: ${NOTIFY_TEMPLATE_ID_FARMER_APPLY_LOGIN:-644a2a30-7487-4e98-a908-b5ecd82d5225}
      NOTIFY_TEMPLATE_ID_FARMER_REGISTER_INTEREST: ${NOTIFY_TEMPLATE_ID_FARMER_REGISTER_INTEREST:-d4d9f03d-fa93-4ca7-b404-be93559af657}
      NOTIFY_TEMPLATE_ID_DEFRA_ID_REGISTER_INTEREST: ${NOTIFY_TEMPLATE_ID_DEFRA_ID_REGISTER_INTEREST:-8c6d9dc1-127d-4355-a16c-cc5fd522f64f}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REGISTER_YOUR_INTEREST_REQUEST_QUEUE_ADDRESS: ${REGISTER_YOUR_INTEREST_REQUEST_QUEUE_ADDRESS:-ffc-ahwr-register-your-interest-request}${MESSAGE_QUEUE_SUFFIX}
      SERVICE_URI: http://localhost:3000/apply
      CLAIM_SERVICE_URI: http://localhost:3004/claim
      URL_PREFIX: "/apply"
      REGISTER_YOUR_INTEREST_ENABLED: ${REGISTER_YOUR_INTEREST_ENABLED:-true}
      ELIGIBILITY_API_URI: http://host.docker.internal:3010/api
      APPLICATION_API_URI: http://host.docker.internal:3001/api
      DEFRA_ID_TENANT: ${DEFRA_ID_TENANT:-azdcuspoc5}
      DEFRA_ID_POLICY: ${DEFRA_ID_POLICY:-B2C_1A_SIGNUPSIGNINSFI}
      DEFRA_ID_REDIRECT_URI: ${DEFRA_ID_REDIRECT_URI:-http://localhost:3000/apply/signin-oidc}
      DEFRA_ID_JWT_ISSUER_ID: ${DEFRA_ID_JWT_ISSUER_ID:-64c9d4f5-a560-4b65-9004-6d1e5ccee51d}
      DEFRA_ID_CLIENT_ID: ${DEFRA_ID_CLIENT_ID:-83d2b160-74ce-4356-9709-3f8da7868e35}
      DEFRA_ID_CLIENT_SECRET: ${DEFRA_ID_CLIENT_SECRET:-changeme}
      DEFRA_ID_SERVICE_ID: ${DEFRA_ID_SERVICE_ID:-2a672ee6-7750-ed11-bba3-000d3adf7047}
      RPA_HOST_NAME: ${RPA_HOST_NAME:-https://dev-internal-gateway.trade.azure.defra.cloud}
      RPA_GET_PERSON_SUMMARY_URL: ${RPA_GET_PERSON_SUMMARY_URL:-/rural-payments-vet-visits/v1/person/3337243/summary}
      RPA_GET_ORGANISATION_PERMISSIONS_URL: ${RPA_GET_ORGANISATION_PERMISSIONS_URL:-/rural-payments-vet-visits/v1/SitiAgriApi/authorisation/organisation/organisationId/authorisation}
      RPA_GET_ORGANISATION_URL: ${RPA_GET_ORGANISATION_URL:-/rural-payments-vet-visits/v1/organisation/organisationId}
      RPA_GET_CPH_NUMBERS_URL: ${RPA_GET_CPH_NUMBERS_URL:-/rural-payments-vet-visits/v1/SitiAgriApi/cph/organisation/organisationId/cph-numbers}
      APIM_OCP_SUBSCRIPTION_KEY: ${APIM_OCP_SUBSCRIPTION_KEY:-changeme}
      APIM_HOST_NAME: ${APIM_HOST_NAME:-https://login.microsoftonline.com}
      APIM_OAUTH_PATH: ${APIM_OAUTH_PATH:-/c9d74090-b4e6-4b04-981d-e6757a160812/oauth2/v2.0/token}
      APIM_CLIENT_ID: ${APIM_CLIENT_ID:-changeme}
      APIM_CLIENT_SECRET: ${APIM_CLIENT_SECRET:-changeme}
      APIM_SCOPE: ${APIM_SCOPE:-api://dev-futuretrade-int.defra.gov.uk/.default}
      TERMS_AND_CONDITIONS_URL: ${TERMS_AND_CONDITIONS_URL:-http://localhost:3000/apply/terms/v3}
      DATE_OF_TESTING_ENABLED: ${DATE_OF_TESTING_ENABLED:-false}
      BLOB_STORAGE_CONNECTION_STRING: ${BLOB_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=https;AccountName=devffcinfst1001;AccountKey=KWCmotG9/1U0r4pxHplFtv0u5C8w2HxCmN+Ooq6eV3HxDOGA/08c/Czk6RlVtqAZYfqvSgU/7DiEhnHTQz/Tng==;EndpointSuffix=core.windows.net}
      BLOB_STORAGE_ACCOUNT_NAME: ${BLOB_STORAGE_ACCOUNT_NAME:-devffcinfst1001}
      BLOB_STORAGE_CONTAINER_NAME: ${BLOB_STORAGE_CONTAINER_NAME:-ffc-grants-water-dev}
      USE_BLOB_STORAGE_CONNECTION_STRING: ${USE_BLOB_STORAGE_CONNECTION_STRING:-true}
