version: "3.8"

services:
  ffc-future-grants-apply:
    command: npm run start:watch
    build:
      target: development
    image: ffc-future-grants-apply-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/

  zap-baseline-scan:
    image: owasp/zap2docker-stable:2.14.0
    command: zap-baseline.py -t http://ffc-future-grants-apply:${PORT:-3000} -c config/zap.conf -r test-output/zap-report.html -a -d -I
    depends_on:
      - ffc-future-grants-apply
    volumes:
      - ./test-output/:/zap/wrk/test-output/
      - ./zap/:/zap/wrk/config/