{{- if .Values.aadPodIdentity }}
{{- include "ffc-helm-library.azure-identity" (list . "ffc-future-grants-apply.azure-identity") -}}
{{- end }}
{{- define "ffc-future-grants-apply.azure-identity" -}}
{{- end -}}
