{{- include "ffc-helm-library.container-config-map" (list . "ffc-future-grants-apply.config-map") -}}
{{- define "ffc-future-grants-apply.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  NAMESPACE: {{ quote .Values.namespace }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  APPLICATIONREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationRequestQueueAddress }}
  APPLICATIONRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.applicationResponseQueueAddress }}
  EVENT_QUEUE_ADDRESS: {{ .Values.container.eventQueueAddress }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey}}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  {{- end }}
  {{- if .Values.pr }}
  REDIS_PARTITION: {{ .Values.container.redisPartition }}-{{ .Values.pr }}
  {{ else }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
  {{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  SERVICE_URI: {{ quote .Values.container.serviceUri }}
  CLAIM_SERVICE_URI: {{ quote .Values.container.claimServiceUri }}
  URL_PREFIX: {{ quote .Values.container.urlPrefix }}
  REGISTER_YOUR_INTEREST_ENABLED: {{ quote .Values.container.registerYourInterestEnabled }}
  REGISTER_YOUR_INTEREST_REQUEST_QUEUE_ADDRESS: {{ quote .Values.container.registerYourInterestRequestQueueAddress }}
  DEFRA_ID_TENANT: {{ quote .Values.container.defraIdTenant }}
  DEFRA_ID_POLICY: {{ quote .Values.container.defraIdPolicy }}
  DEFRA_ID_REDIRECT_URI: {{ quote .Values.container.defraIdRedirectUri }}
  DEFRA_ID_JWT_ISSUER_ID: {{ quote .Values.container.defraIdJwtIssuerId }}
  RPA_HOST_NAME: {{ quote .Values.container.rpaHostname }}
  RPA_GET_PERSON_SUMMARY_URL: {{ quote .Values.container.rpaGetPersonSummaryUrl }}
  RPA_GET_ORGANISATION_PERMISSIONS_URL: {{ quote .Values.container.rpaGetOrganisationPermissionsUrl }}
  RPA_GET_ORGANISATION_URL: {{ quote .Values.container.rpaGetOrganisationUrl }}
  RPA_GET_CPH_NUMBERS_URL: {{ quote .Values.container.rpaGetCphNumbersUrl }}
  APIM_HOST_NAME: {{ quote .Values.container.apimHostname }}
  APIM_OAUTH_PATH: {{ quote .Values.container.apimOAuthPath }}
  APIM_SCOPE: {{ quote .Values.container.apimScope }}
  WRECK_HTTP_TIMEOUT_MILLISECONDS: {{ quote .Values.wreckHttp.timeoutMilliseconds }}
  TERMS_AND_CONDITIONS_URL: {{ quote .Values.container.termsAndConditionsUrl }}
  DATE_OF_TESTING_ENABLED: {{ quote .Values.container.dateOfTestingEnabled }}
{{- end -}}
