{{- include "ffc-helm-library.container-secret" (list . "ffc-future-grants-apply.container-secret") -}}
{{- define "ffc-future-grants-apply.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
  DEFRA_ID_CLIENT_SECRET: {{ .Values.container.defraIdClientSecret | quote }}
  DEFRA_ID_CLIENT_ID: {{ .Values.container.defraIdClientId | quote }}
  DEFRA_ID_SERVICE_ID: {{ .Values.container.defraIdServiceId | quote }}
  APIM_OCP_SUBSCRIPTION_KEY: {{ .Values.container.apimOcpSubscriptionKey | quote }}
  APIM_CLIENT_ID: {{ .Values.container.apimClientId | quote }}
  APIM_CLIENT_SECRET: {{ .Values.container.apimClientSecret | quote }}
{{- end -}}
