environment: development
name: ffc-future-grants-apply
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-future-grants-apply

labels: {}

aadPodIdentity: true

appInsights:
  connectionString:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-future-grants-apply-config-map

containerSecret:
  name: ffc-future-grants-apply-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 2
  maxReplicas: 4
  priorityClassName: high
  replicas: 2
  restartPolicy: Always

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 400Mi
  limitCpu: 400m
  applicationRequestQueueAddress: ffc-ahwr-application-request
  applicationResponseQueueAddress: ffc-ahwr-application-response
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  eventQueueAddress: ffc-ahwr-event
  googleTagManagerKey:
  imagePullPolicy: IfNotPresent
  messageQueueHost: namespace.servicebus.windows.net
  port: 3000
  redisHostname: redis-hostname.default
  redisPartition: ffc-future-grants-apply
  redisPassword: redis
  redisPort: 6379
  serviceUri:
  claimServiceUri:
  urlPrefix: /apply
  termsAndConditionsUrl:
  eligibilityApiUri:
  applicationApiUri:
  registerYourInterestEnabled:
  registerYourInterestRequestQueueAddress: ffc-ahwr-register-your-interest-request
  defraIdTenant:
  defraIdRedirectUri:
  defraIdJwtIssuerId:
  defraIdClientId:
  defraIdClientSecret:
  defraIdServiceId:
  defraIdPolicy:
  rpaHostname:
  rpaGetPersonSummaryUrl:
  rpaGetOrganisationPermissionsUrl:
  rpaGetOrganisationUrl:
  rpaGetCphNumbersUrl:
  apimOcpSubscriptionKey:
  apimHostname:
  apimOAuthPath:
  apimClientId:
  apimClientSecret:
  apimScope:
  dateOfTestingEnabled:

ingress:
  class: nginx
  endpoint: ffc-future-grants
  server: value.replaced.from.app.config
  path: /apply
  type: minion

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  failureThreshold: 5
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 30
  failureThreshold: 5
  timeoutSeconds: 5

service:
  port: 80
  type: ClusterIP

wreckHttp:
  timeoutMilliseconds: 10000
