{{- include "ffc-helm-library.deployment" (list . "ffc-future-grants-apply.deployment") -}}
{{- define "ffc-future-grants-apply.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-future-grants-apply.container") }}
{{- end -}}
